name: Shorebird Patch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  patch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: Get Packages
        run: flutter pub get

      - name: Run Patch
        run: |
          yes | shorebird patch android --force || echo "⚠️ Warning ignored"
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

      - name: Send Telegram
        run: |
          APK_PATH=$(find . -name "*.apk" | grep -v "unsigned" | head -n 1)
          if [ -n "$APK_PATH" ]; then
            curl -F document=@"$APK_PATH" \
                 -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
                 -F caption="🚀 New Patch Sent!" \
                 https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument
          fi
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
